# Generated by Django 5.0.6 on 2024-06-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("On Track", "On Track"),
                            ("At Risk", "At Risk"),
                            ("Overdue", "Overdue"),
                            ("Complete", "Complete"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
