# Generated by Django 5.0.6 on 2024-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0002_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="owner",
            field=models.TextField(default="henry"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("On Track", "On Track"),
                    ("At Risk", "At Risk"),
                    ("Overdue", "Overdue"),
                    ("Complete", "Complete"),
                ],
                max_length=20,
            ),
        ),
    ]
