# Generated by Django 5.0.6 on 2024-06-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0003_task_owner_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.TextField(max_length=50),
        ),
    ]
